"""initial

Revision ID: 0354ae9d502b
Revises: 
Create Date: 2026-03-05 13:04:27.565690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0354ae9d502b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='ID пользователя из таблицы users (NULL для API-запросов)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False, comment='fact | chat'),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False, comment='True если вернули заглушку из-за ошибки'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Время ответа API в миллисекундах'),
    sa.Column('error', sa.String(length=255), nullable=True, comment='Текст ошибки если запрос не удался'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_logs_created_at'), 'llm_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_logs_request_type'), 'llm_logs', ['request_type'], unique=False)
    op.create_index(op.f('ix_llm_logs_user_id'), 'llm_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_logs_user_id'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_request_type'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_created_at'), table_name='llm_logs')
    op.drop_table('llm_logs')
    # ### end Alembic commands ###
