"""LLM application layer module."""

from .commands import (
    AskGeneticsQuestionCommand,
    AskGeneticsQuestionHandler,
    ChatHistoryItem,
    GenerateGeneFactCommand,
    GenerateGeneFactHandler,
)
from .dto import (
    ChatAnswerOutput,
    GeneFactOutput,
    LLMCompletionOutput,
    LLMLogListOutput,
    LLMLogOutput,
    LLMStatsOutput,
)
from .interfaces import LLMGenerationService
from .queries import (
    GetFailedLLMLogsHandler,
    GetFailedLLMLogsQuery,
    GetLLMLogByIdHandler,
    GetLLMLogByIdQuery,
    GetLLMLogsHandler,
    GetLLMLogsQuery,
    GetLLMStatsHandler,
    GetLLMStatsQuery,
    GetLLMLogsByDateRangeHandler,
    GetLLMLogsByDateRangeQuery,
    GetLLMLogsByRequestTypeHandler,
    GetLLMLogsByRequestTypeQuery,
    GetSlowLLMLogsHandler,
    GetSlowLLMLogsQuery,
    GetUserLLMLogsHandler,
    GetUserLLMLogsQuery,
)

__all__ = [
    "LLMGenerationService",
    "LLMCompletionOutput",
    "GeneFactOutput",
    "ChatAnswerOutput",
    "LLMLogOutput",
    "LLMLogListOutput",
    "LLMStatsOutput",
    "ChatHistoryItem",
    "GenerateGeneFactCommand",
    "GenerateGeneFactHandler",
    "AskGeneticsQuestionCommand",
    "AskGeneticsQuestionHandler",
    "GetLLMLogByIdHandler",
    "GetLLMLogByIdQuery",
    "GetLLMLogsHandler",
    "GetLLMLogsQuery",
    "GetLLMStatsHandler",
    "GetLLMStatsQuery",
    "GetUserLLMLogsHandler",
    "GetUserLLMLogsQuery",
    "GetFailedLLMLogsHandler",
    "GetFailedLLMLogsQuery",
    "GetSlowLLMLogsHandler",
    "GetSlowLLMLogsQuery",
    "GetLLMLogsByRequestTypeHandler",
    "GetLLMLogsByRequestTypeQuery",
    "GetLLMLogsByDateRangeHandler",
    "GetLLMLogsByDateRangeQuery",
]
